In [527]:
from __future__ import print_function
import pandas as pd
import numpy as np

In [528]:
s = pd.Series([1,3,6,np.nan,4,1]) # similar with 1D numpy
print(s)

0    1.0
1    3.0
2    6.0
3    NaN
4    4.0
5    1.0
dtype: float64


In [529]:
dates = pd.date_range('20160101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])
print(df['B'])

2016-01-01   -0.022219
2016-01-02    0.273933
2016-01-03   -0.157412
2016-01-04    1.806497
2016-01-05   -0.214931
2016-01-06    0.420641
Freq: D, Name: B, dtype: float64


In [530]:
df2 = pd.DataFrame({'A' : 1.,
                       'B' : pd.Timestamp('20130102'),
                        'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                        'D' : np.array([3] * 4,dtype='int32'),
                        'E' : pd.Categorical(["test","train","test","train"]),
                        'F' : 'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [531]:
print(df2.dtypes)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [532]:
print(df.index)

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')


In [533]:
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


In [534]:
print(df.values)

[[ 0.32673383 -0.02221862 -1.12199057 -1.5144343 ]
 [ 0.12592353  0.27393305  0.86520437 -0.52822245]
 [-0.51134497 -0.15741238  0.17380124 -0.95841171]
 [ 0.05960323  1.80649693 -0.70009058 -0.27465618]
 [ 0.60674631 -0.21493104 -0.90487931  0.88634359]
 [-1.85187723  0.42064144 -0.23206821  0.37925133]]


In [535]:
print(df.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.207369  0.351085 -0.320004 -0.335022
std    0.886252  0.754628  0.746461  0.874359
min   -1.851877 -0.214931 -1.121991 -1.514434
25%   -0.368608 -0.123614 -0.853682 -0.850864
50%    0.092763  0.125857 -0.466079 -0.401439
75%    0.276531  0.383964  0.072334  0.215774
max    0.606746  1.806497  0.865204  0.886344


In [536]:
print(df.T)

   2016-01-01  2016-01-02  2016-01-03  2016-01-04  2016-01-05  2016-01-06
A    0.326734    0.125924   -0.511345    0.059603    0.606746   -1.851877
B   -0.022219    0.273933   -0.157412    1.806497   -0.214931    0.420641
C   -1.121991    0.865204    0.173801   -0.700091   -0.904879   -0.232068
D   -1.514434   -0.528222   -0.958412   -0.274656    0.886344    0.379251


In [537]:
print(df.sort_index(axis=1, ascending=False))

                   D         C         B         A
2016-01-01 -1.514434 -1.121991 -0.022219  0.326734
2016-01-02 -0.528222  0.865204  0.273933  0.125924
2016-01-03 -0.958412  0.173801 -0.157412 -0.511345
2016-01-04 -0.274656 -0.700091  1.806497  0.059603
2016-01-05  0.886344 -0.904879 -0.214931  0.606746
2016-01-06  0.379251 -0.232068  0.420641 -1.851877


In [538]:
print(df.sort_values(by='B'))

                   A         B         C         D
2016-01-05  0.606746 -0.214931 -0.904879  0.886344
2016-01-03 -0.511345 -0.157412  0.173801 -0.958412
2016-01-01  0.326734 -0.022219 -1.121991 -1.514434
2016-01-02  0.125924  0.273933  0.865204 -0.528222
2016-01-06 -1.851877  0.420641 -0.232068  0.379251
2016-01-04  0.059603  1.806497 -0.700091 -0.274656


# Numpy 属性
这次我们会介绍几种 numpy 的属性:
ndim：维度
shape：行数和列数
size：元素个数

In [539]:
import numpy as np #为了方便使用numpy 采用np简写
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)

[[1 2 3]
 [2 3 4]]


## numpy 的几种属性

In [540]:
print('number of dim:',array.ndim)  # 维度
# number of dim: 2

print('shape :',array.shape)    # 行数和列数
# shape : (2, 3)

print('size:',array.size)   # 元素个数
# size: 6

number of dim: 2
shape : (2, 3)
size: 6


# Numpy 的创建 array
## 关键字
array：创建数组
dtype：指定数据类型
zeros：创建数据全为0
ones：创建数据全为1
empty：创建数据接近0
arrange：按指定范围创建数据
linspace：创建线段
## 创建数组

In [541]:
a = np.array([2,23,4])  # list 1d
print(a)
# [2 23 4]

[ 2 23  4]


## 指定数据 dtype

In [542]:
a = np.array([2,23,4],dtype=np.int64)
print(a.dtype)
# int 64
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)
# int32
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)
# float64
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)
# float32

int64
int32
float64
float32


D:\0ilraypan\python_work\mytrader\Lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


## 创建特定数据

In [543]:
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)
"""
[[ 2 23  4]
 [ 2 32  4]]
"""

[[ 2 23  4]
 [ 2 32  4]]


'\n[[ 2 23  4]\n [ 2 32  4]]\n'

### 创建全零数组

In [544]:
a = np.zeros((3,4)) # 数据全为0，3行4列
"""
array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])
"""




'\narray([[ 0.,  0.,  0.,  0.],\n       [ 0.,  0.,  0.,  0.],\n       [ 0.,  0.,  0.,  0.]])\n'

### 创建全一数组, 同时也能指定这些特定数据的 dtype:

In [545]:
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
"""
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])
"""

D:\0ilraypan\python_work\mytrader\Lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


'\narray([[1, 1, 1, 1],\n       [1, 1, 1, 1],\n       [1, 1, 1, 1]])\n'

### 创建全空数组, 其实每个值都是接近于零的数:

In [546]:
a = np.empty((3,4)) # 数据为empty，3行4列
"""
array([[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,
          1.48219694e-323],
       [  1.97626258e-323,   2.47032823e-323,   2.96439388e-323,
          3.45845952e-323],
       [  3.95252517e-323,   4.44659081e-323,   4.94065646e-323,
          5.43472210e-323]])
"""

'\narray([[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,\n          1.48219694e-323],\n       [  1.97626258e-323,   2.47032823e-323,   2.96439388e-323,\n          3.45845952e-323],\n       [  3.95252517e-323,   4.44659081e-323,   4.94065646e-323,\n          5.43472210e-323]])\n'

### 用arange 创建连续数组:

In [547]:
a = np.arange(10,20,2) # 10-19 的数据，2步长
"""
array([10, 12, 14, 16, 18])
"""


'\narray([10, 12, 14, 16, 18])\n'

### 使用 reshape 改变数据的形状

In [548]:
a = np.arange(12).reshape((3,4))    # 3行4列，0到11
"""
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
"""


'\narray([[ 0,  1,  2,  3],\n       [ 4,  5,  6,  7],\n       [ 8,  9, 10, 11]])\n'

### 用 linspace 创建线段型数据:

In [549]:
a = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
"""
array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])
"""


'\narray([  1.        ,   1.47368421,   1.94736842,   2.42105263,\n         2.89473684,   3.36842105,   3.84210526,   4.31578947,\n         4.78947368,   5.26315789,   5.73684211,   6.21052632,\n         6.68421053,   7.15789474,   7.63157895,   8.10526316,\n         8.57894737,   9.05263158,   9.52631579,  10.        ])\n'

### 同样也能进行 reshape 工作:

In [550]:
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
"""
array([[  1.        ,   1.47368421,   1.94736842,   2.42105263],
       [  2.89473684,   3.36842105,   3.84210526,   4.31578947],
       [  4.78947368,   5.26315789,   5.73684211,   6.21052632],
       [  6.68421053,   7.15789474,   7.63157895,   8.10526316],
       [  8.57894737,   9.05263158,   9.52631579,  10.        ]])
"""

'\narray([[  1.        ,   1.47368421,   1.94736842,   2.42105263],\n       [  2.89473684,   3.36842105,   3.84210526,   4.31578947],\n       [  4.78947368,   5.26315789,   5.73684211,   6.21052632],\n       [  6.68421053,   7.15789474,   7.63157895,   8.10526316],\n       [  8.57894737,   9.05263158,   9.52631579,  10.        ]])\n'

# Numpy 基础运算1
### numpy 的几种基本运算

In [551]:
import numpy as np
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)              # array([0, 1, 2, 3])

### 减

In [552]:
c=a-b  # array([10, 19, 28, 37])
print(c)

[10 19 28 37]


### 加

In [553]:
c=a+b   # array([10, 21, 32, 43])
print(c)

[10 21 32 43]


### 乘

In [554]:
c=a*b   # array([  0,  20,  60, 120])
print(c)

[  0  20  60 120]


### 二次方

In [555]:
c=b**2  # array([0, 1, 4, 9])
print(c)

[0 1 4 9]


### sin()

In [556]:
c=10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


### 逻辑判断

In [557]:
print(b<3)

[ True  True  True False]


### 二维矩阵

In [558]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
# array([[1, 1],
#       [0, 1]])
print(b)
# array([[0, 1],
#       [2, 3]])

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


### 矩阵相乘

In [559]:
c_dot = np.dot(a,b)
# array([[2, 4],
#       [2, 3]])
print(c_dot)

[[2 4]
 [2 3]]


### 矩阵相乘2

In [560]:
c_dot_2 = a.dot(b)
# array([[2, 4],
#       [2, 3]])
print(c_dot_2)

[[2 4]
 [2 3]]


### 数组sum(), min(), max()的使用

In [561]:
import numpy as np
a=np.random.random((2,4))
print(a)
# array([[ 0.94692159,  0.20821798,  0.35339414,  0.2805278 ],
#       [ 0.04836775,  0.04023552,  0.44091941,  0.21665268]])

[[0.21587027 0.24857397 0.63553471 0.25055656]
 [0.1587139  0.23753429 0.91289363 0.76272927]]


In [562]:
np.sum(a)   # 4.4043622002745959

3.4224066027683206

In [563]:
np.min(a)   # 0.23651223533671784

0.15871390267561514

In [564]:
np.max(a)   # 0.90438450240606416

0.9128936319774525

In [565]:
print("a =",a)
# a = [[ 0.23651224  0.41900661  0.84869417  0.46456022]
# [ 0.60771087  0.9043845   0.36603285  0.55746074]]

a = [[0.21587027 0.24857397 0.63553471 0.25055656]
 [0.1587139  0.23753429 0.91289363 0.76272927]]


In [566]:
print("sum =",np.sum(a,axis=1))
# sum = [ 1.96877324  2.43558896]

sum = [1.35053552 2.07187109]


In [567]:
print("min =",np.min(a,axis=0))
# min = [ 0.23651224  0.41900661  0.36603285  0.46456022]

min = [0.1587139  0.23753429 0.63553471 0.25055656]


In [568]:
print("max =",np.max(a,axis=1))
# max = [ 0.84869417  0.9043845 ]

max = [0.63553471 0.91289363]


# Numpy 基础运算2

In [569]:
import numpy as np
A = np.arange(2,14).reshape((3,4))

# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])

print(np.argmin(A))    # 0
print(np.argmax(A))    # 11

0
11


## numpy 的几种基本运算
### 计算统计中的均值

In [570]:
print(np.mean(A))        # 7.5
print(np.average(A))     # 7.5

7.5
7.5


mean()函数还有另外一种写法：

In [571]:
print(A.mean())          # 7.5


7.5


求解中位数的函数

In [572]:
#print(A.median())       # 7.5

### 累加函数

In [573]:
print(np.cumsum(A))

# [2 5 9 14 20 27 35 44 54 65 77 90]

[ 2  5  9 14 20 27 35 44 54 65 77 90]


### 累差运算函数

In [574]:
print(np.diff(A))

# [[1 1 1]
#  [1 1 1]
#  [1 1 1]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## nonzero()函数

In [575]:
print(np.nonzero(A))

# (array([0,0,0,0,1,1,1,1,2,2,2,2]),array([0,1,2,3,0,1,2,3,0,1,2,3]))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


## 从小到大排序操作

In [576]:
import numpy as np
A = np.arange(14,2, -1).reshape((3,4))
print(A)
# array([[14, 13, 12, 11],
#       [10,  9,  8,  7],
#       [ 6,  5,  4,  3]])

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [577]:
print(np.sort(A))
# array([[11,12,13,14]
#        [ 7, 8, 9,10]
#        [ 3, 4, 5, 6]])

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


### 矩阵的转置有两种表示方法：

In [578]:
print(np.transpose(A))
print(A.T)

# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


### clip()函数

In [579]:
print(A)
# array([[14,13,12,11]
#        [10, 9, 8, 7]
#        [ 6, 5, 4, 3]])

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [580]:
print(np.clip(A,5,9))
# array([[ 9, 9, 9, 9]
#        [ 9, 9, 8, 7]
#        [ 6, 5, 5, 5]])

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


# Numpy 索引
## 一维索引

In [581]:
import numpy as np
A = np.arange(3,15)

# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

print(A[3])    # 6

6


### 矩阵转换为二维的

In [582]:
A = np.arange(3,15).reshape((3,4))
"""
array([[ 3,  4,  5,  6]
       [ 7,  8,  9, 10]
       [11, 12, 13, 14]])
"""

print(A[2])
# [11 12 13 14]

[11 12 13 14]


## 二维索引

In [583]:
print(A[1][1])      # 8
print(A[1, 1])      # 8
print(A[1, 1:3])    # [8 9]

8
8
[8 9]


In [584]:
for row in A:
    print(row)
"""
[ 3,  4,  5, 6]
[ 7,  8,  9, 10]
[11, 12, 13, 14]
"""

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


'\n[ 3,  4,  5, 6]\n[ 7,  8,  9, 10]\n[11, 12, 13, 14]\n'

In [585]:
for column in A.T:
    print(column)
"""
[ 3,  7,  11]
[ 4,  8,  12]
[ 5,  9,  13]
[ 6, 10,  14]
"""

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


'\n[ 3,  7,  11]\n[ 4,  8,  12]\n[ 5,  9,  13]\n[ 6, 10,  14]\n'

In [586]:
import numpy as np
A = np.arange(3,15).reshape((3,4))

print(A.flatten())
# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


# Numpy array 合并
## np.vstack()

In [587]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])

print(np.vstack((A,B)))    # vertical stack
"""
[[1,1,1]
 [2,2,2]]
"""


[[1 1 1]
 [2 2 2]]


'\n[[1,1,1]\n [2,2,2]]\n'

In [588]:
C = np.vstack((A,B))
print(A.shape,C.shape)

# (3,) (2,3)


(3,) (2, 3)


## np.hstack()

In [589]:
D = np.hstack((A,B))       # horizontal stack

print(D)
# [1,1,1,2,2,2]

print(A.shape,D.shape)
# (3,) (6,)

[1 1 1 2 2 2]
(3,) (6,)


## np.newaxis()

In [590]:
print(A[np.newaxis,:])
# [[1 1 1]]

print(A[np.newaxis,:].shape)
# (1,3)

print(A[:,np.newaxis])
"""
[[1]
[1]
[1]]
"""

print(A[:,np.newaxis].shape)
# (3,1)



[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [591]:
import numpy as np
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack

print(D)
"""
[[1 2]
[1 2]
[1 2]]
"""

print(A.shape,D.shape)
# (3,1) (3,2)


[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


## np.concatenate()

In [592]:
C = np.concatenate((A,B,B,A),axis=0)

print(C)
"""
array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1]])
"""

D = np.concatenate((A,B,B,A),axis=1)

print(D)
"""
array([[1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1]])
"""




[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


'\narray([[1, 2, 2, 1],\n       [1, 2, 2, 1],\n       [1, 2, 2, 1]])\n'

# Numpy array 分割
## 创建数据

In [593]:
import numpy as np
A = np.arange(12).reshape((3, 4))
print(A)
"""
array([[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]])
"""

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


'\narray([[ 0,  1,  2,  3],\n    [ 4,  5,  6,  7],\n    [ 8,  9, 10, 11]])\n'

## 纵向分割

In [594]:
print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


'\n[array([[0, 1],\n        [4, 5],\n        [8, 9]]), array([[ 2,  3],\n        [ 6,  7],\n        [10, 11]])]\n'

## 横向分割

In [595]:
print(np.split(A, 3, axis=0))

# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]




[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


# 错误分割

In [596]:
#print(np.split(A, 3, axis=1))

# ValueError: array split does not result in an equal division

## 不等量的分割

In [597]:
print(np.array_split(A, 3, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]
"""


[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


'\n[array([[0, 1],\n        [4, 5],\n        [8, 9]]), array([[ 2],\n        [ 6],\n        [10]]), array([[ 3],\n        [ 7],\n        [11]])]\n'

## 其他的分割方式



In [598]:
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))

# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [599]:
print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


'\n[array([[0, 1],\n       [4, 5],\n       [8, 9]]), array([[ 2,  3],\n        [ 6,  7],\n        [10, 11]])]\n'

# Numpy copy & deep copy
## = 的赋值方式会带有关联性

In [600]:
import numpy as np

a = np.arange(4)
# array([0, 1, 2, 3])

b = a
c = a
d = b


In [601]:
a[0] = 11
print(a)
# array([11,  1,  2,  3])

[11  1  2  3]


In [602]:
b is a  # True

True

In [603]:
c is a  # True

True

In [604]:
d is a  # True

True

In [605]:
d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)            # array([11, 22, 33,  3])


[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


## copy() 的赋值方式没有关联性


In [606]:
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
