In [7]:
# View more python tutorials on my Youtube and Youku channel!!!

# Youtube video tutorial: https://www.youtube.com/channel/UCdyjiB5H8Pu7aDTNVXTTpcg
# Youku video tutorial: http://i.youku.com/pythontutorial

"""
Please note, this code is only for python 3+. If you are using python 2+, please modify the code accordingly.
"""
from __future__ import print_function
import pandas as pd
import numpy as np

In [8]:
s = pd.Series([1,3,6,np.nan,4,1]) # similar with 1D numpy
print(s)

0    1.0
1    3.0
2    6.0
3    NaN
4    4.0
5    1.0
dtype: float64


In [9]:
dates = pd.date_range('20160101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])
print(df['B'])

2016-01-01   -0.496498
2016-01-02    1.975814
2016-01-03    0.290873
2016-01-04   -1.279505
2016-01-05   -0.170295
2016-01-06   -0.035805
Freq: D, Name: B, dtype: float64


In [10]:
df2 = pd.DataFrame({'A' : 1.,
                       'B' : pd.Timestamp('20130102'),
                        'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                        'D' : np.array([3] * 4,dtype='int32'),
                        'E' : pd.Categorical(["test","train","test","train"]),
                        'F' : 'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [11]:
print(df2.dtypes)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [12]:
print(df.index)

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')


In [13]:
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


In [14]:
print(df.values)

[[ 0.0449985  -0.49649753 -0.5450636   1.46646345]
 [ 0.89048294  1.97581403  0.26276854 -1.47881523]
 [-1.26710479  0.29087306  1.25131731 -1.32774038]
 [-0.92256547 -1.27950525 -0.288203   -0.60323403]
 [ 0.93347765 -0.17029523 -0.3594684  -0.25570868]
 [-0.86914774 -0.03580465  1.59694773 -0.37564336]]


In [15]:
print(df.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.198310  0.047431  0.319716 -0.429113
std    0.963587  1.085254  0.903454  1.055070
min   -1.267105 -1.279505 -0.545064 -1.478815
25%   -0.909211 -0.414947 -0.341652 -1.146614
50%   -0.412075 -0.103050 -0.012717 -0.489439
75%    0.679112  0.209204  1.004180 -0.285692
max    0.933478  1.975814  1.596948  1.466463


In [16]:
print(df.T)

   2016-01-01  2016-01-02  2016-01-03  2016-01-04  2016-01-05  2016-01-06
A    0.044998    0.890483   -1.267105   -0.922565    0.933478   -0.869148
B   -0.496498    1.975814    0.290873   -1.279505   -0.170295   -0.035805
C   -0.545064    0.262769    1.251317   -0.288203   -0.359468    1.596948
D    1.466463   -1.478815   -1.327740   -0.603234   -0.255709   -0.375643


In [17]:
print(df.sort_index(axis=1, ascending=False))

                   D         C         B         A
2016-01-01  1.466463 -0.545064 -0.496498  0.044998
2016-01-02 -1.478815  0.262769  1.975814  0.890483
2016-01-03 -1.327740  1.251317  0.290873 -1.267105
2016-01-04 -0.603234 -0.288203 -1.279505 -0.922565
2016-01-05 -0.255709 -0.359468 -0.170295  0.933478
2016-01-06 -0.375643  1.596948 -0.035805 -0.869148


In [18]:
print(df.sort_values(by='B'))

                   A         B         C         D
2016-01-04 -0.922565 -1.279505 -0.288203 -0.603234
2016-01-01  0.044998 -0.496498 -0.545064  1.466463
2016-01-05  0.933478 -0.170295 -0.359468 -0.255709
2016-01-06 -0.869148 -0.035805  1.596948 -0.375643
2016-01-03 -1.267105  0.290873  1.251317 -1.327740
2016-01-02  0.890483  1.975814  0.262769 -1.478815


In [19]:
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)

[[1 2 3]
 [2 3 4]]


In [20]:
print('number of dim:',array.ndim)  # 维度
# number of dim: 2

print('shape :',array.shape)    # 行数和列数
# shape : (2, 3)

print('size:',array.size)   # 元素个数
# size: 6

number of dim: 2
shape : (2, 3)
size: 6


In [24]:
a = np.array([2,23,4])  # list 1d
print(a)
# [2 23 4]

[ 2 23  4]


In [38]:
a = np.array([2,23,4],dtype=np.int64)
print(a.dtype)
# int 64
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)
# int32
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)
# float64
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)
# float32

int64
int32
float64
float32


<ipython-input-38-69a746334b07>:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.array([2,23,4],dtype=np.float)


In [30]:
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)
"""
[[ 2 23  4]
 [ 2 32  4]]
"""

[[ 2 23  4]
 [ 2 32  4]]


'\n[[ 2 23  4]\n [ 2 32  4]]\n'

In [31]:
a = np.zeros((3,4)) # 数据全为0，3行4列
"""
array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])
"""


'\narray([[ 0.,  0.,  0.,  0.],\n       [ 0.,  0.,  0.,  0.],\n       [ 0.,  0.,  0.,  0.]])\n'

In [33]:
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
"""
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])
"""

<ipython-input-33-d7165a766655>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列


'\narray([[1, 1, 1, 1],\n       [1, 1, 1, 1],\n       [1, 1, 1, 1]])\n'

In [34]:
a = np.empty((3,4)) # 数据为empty，3行4列
"""
array([[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,
          1.48219694e-323],
       [  1.97626258e-323,   2.47032823e-323,   2.96439388e-323,
          3.45845952e-323],
       [  3.95252517e-323,   4.44659081e-323,   4.94065646e-323,
          5.43472210e-323]])
"""

'\narray([[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,\n          1.48219694e-323],\n       [  1.97626258e-323,   2.47032823e-323,   2.96439388e-323,\n          3.45845952e-323],\n       [  3.95252517e-323,   4.44659081e-323,   4.94065646e-323,\n          5.43472210e-323]])\n'

In [35]:
a = np.arange(10,20,2) # 10-19 的数据，2步长
"""
array([10, 12, 14, 16, 18])
"""


'\narray([10, 12, 14, 16, 18])\n'

In [39]:
a = np.arange(12).reshape((3,4))    # 3行4列，0到11
"""
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
"""


'\narray([[ 0,  1,  2,  3],\n       [ 4,  5,  6,  7],\n       [ 8,  9, 10, 11]])\n'

In [42]:
a = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
"""
array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])
"""


'\narray([[  1.        ,   1.47368421,   1.94736842,   2.42105263],\n       [  2.89473684,   3.36842105,   3.84210526,   4.31578947],\n       [  4.78947368,   5.26315789,   5.73684211,   6.21052632],\n       [  6.68421053,   7.15789474,   7.63157895,   8.10526316],\n       [  8.57894737,   9.05263158,   9.52631579,  10.        ]])\n'

In [ ]:
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
"""
array([[  1.        ,   1.47368421,   1.94736842,   2.42105263],
       [  2.89473684,   3.36842105,   3.84210526,   4.31578947],
       [  4.78947368,   5.26315789,   5.73684211,   6.21052632],
       [  6.68421053,   7.15789474,   7.63157895,   8.10526316],
       [  8.57894737,   9.05263158,   9.52631579,  10.        ]])
"""

In [49]:
import numpy as np
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)              # array([0, 1, 2, 3])

[10 19 28 37]
[10 21 32 43]


In [50]:
c=a-b  # array([10, 19, 28, 37])
print(c)

[10 19 28 37]


In [51]:
c=a+b   # array([10, 21, 32, 43])
print(c)

[10 21 32 43]


In [53]:
c=a*b   # array([  0,  20,  60, 120])
print(c)

[  0  20  60 120]


In [54]:
c=b**2  # array([0, 1, 4, 9])
print(c)

[0 1 4 9]


In [55]:
c=10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [56]:
print(b<3)

[ True  True  True False]


In [57]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
# array([[1, 1],
#       [0, 1]])

print(b)
# array([[0, 1],
#       [2, 3]])


[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [61]:
c_dot = np.dot(a,b)
# array([[2, 4],
#       [2, 3]])
print(c_dot)

[[2 4]
 [2 3]]


In [62]:
c_dot_2 = a.dot(b)
# array([[2, 4],
#       [2, 3]])
print(c_dot_2)

[[2 4]
 [2 3]]


In [63]:
import numpy as np
a=np.random.random((2,4))
print(a)
# array([[ 0.94692159,  0.20821798,  0.35339414,  0.2805278 ],
#       [ 0.04836775,  0.04023552,  0.44091941,  0.21665268]])

[[0.54804503 0.16090949 0.22479241 0.78522658]
 [0.67025574 0.82395706 0.46936457 0.22031091]]


In [65]:
np.sum(a)   # 4.4043622002745959

3.902861794259104

In [66]:
np.min(a)   # 0.23651223533671784

0.16090949363549623

In [67]:
np.max(a)   # 0.90438450240606416

0.8239570554063008

In [69]:
print("a =",a)
# a = [[ 0.23651224  0.41900661  0.84869417  0.46456022]
# [ 0.60771087  0.9043845   0.36603285  0.55746074]]

a = [[0.54804503 0.16090949 0.22479241 0.78522658]
 [0.67025574 0.82395706 0.46936457 0.22031091]]


In [70]:
print("sum =",np.sum(a,axis=1))
# sum = [ 1.96877324  2.43558896]

sum = [1.71897352 2.18388827]


In [71]:
print("min =",np.min(a,axis=0))
# min = [ 0.23651224  0.41900661  0.36603285  0.46456022]

min = [0.54804503 0.16090949 0.22479241 0.22031091]


In [72]:
print("max =",np.max(a,axis=1))
# max = [ 0.84869417  0.9043845 ]

max = [0.78522658 0.82395706]


In [74]:
import numpy as np
A = np.arange(2,14).reshape((3,4))

# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])

print(np.argmin(A))    # 0
print(np.argmax(A))    # 11

0
11


In [75]:
print(np.mean(A))        # 7.5
print(np.average(A))     # 7.5


7.5
7.5


In [76]:
print(A.mean())          # 7.5


7.5


In [79]:
print(A.median())       # 7.5

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [80]:
print(np.cumsum(A))

# [2 5 9 14 20 27 35 44 54 65 77 90]

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [82]:
print(np.diff(A))

# [[1 1 1]
#  [1 1 1]
#  [1 1 1]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [84]:
print(np.nonzero(A))

# (array([0,0,0,0,1,1,1,1,2,2,2,2]),array([0,1,2,3,0,1,2,3,0,1,2,3]))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [94]:
import numpy as np
A = np.arange(14,2, -1).reshape((3,4))
print(A)
# array([[14, 13, 12, 11],
#       [10,  9,  8,  7],
#       [ 6,  5,  4,  3]])

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [95]:
print(np.sort(A))
# array([[11,12,13,14]
#        [ 7, 8, 9,10]
#        [ 3, 4, 5, 6]])

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [88]:
print(np.transpose(A))
print(A.T)

# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [91]:
print(A)
# array([[14,13,12,11]
#        [10, 9, 8, 7]
#        [ 6, 5, 4, 3]])

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [97]:
print(np.clip(A,5,9))
# array([[ 9, 9, 9, 9]
#        [ 9, 9, 8, 7]
#        [ 6, 5, 5, 5]])

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
