# Numpy 属性
这次我们会介绍几种 numpy 的属性:
ndim：维度
shape：行数和列数
size：元素个数

In [1]:
import numpy as np #为了方便使用numpy 采用np简写
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)

[[1 2 3]
 [2 3 4]]


## numpy 的几种属性

In [2]:
print('number of dim:',array.ndim)  # 维度
# number of dim: 2

print('shape :',array.shape)    # 行数和列数
# shape : (2, 3)

print('size:',array.size)   # 元素个数
# size: 6

number of dim: 2
shape : (2, 3)
size: 6


# Numpy 的创建 array
## 关键字
array：创建数组
dtype：指定数据类型
zeros：创建数据全为0
ones：创建数据全为1
empty：创建数据接近0
arrange：按指定范围创建数据
linspace：创建线段
## 创建数组

In [3]:
a = np.array([2,23,4])  # list 1d
print(a)
# [2 23 4]

[ 2 23  4]


## 指定数据 dtype

In [4]:
a = np.array([2,23,4],dtype=np.int64)
print(a.dtype)
# int 64
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)
# int32
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)
# float64
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)
# float32

int64
int32
float64
float32


D:\0ilraypan\python_work\env\pyqt5\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


## 创建特定数据

In [5]:
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)
"""
[[ 2 23  4]
 [ 2 32  4]]
"""

[[ 2 23  4]
 [ 2 32  4]]


'\n[[ 2 23  4]\n [ 2 32  4]]\n'

### 创建全零数组

In [6]:
a = np.zeros((3,4)) # 数据全为0，3行4列
"""
array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])
"""




'\narray([[ 0.,  0.,  0.,  0.],\n       [ 0.,  0.,  0.,  0.],\n       [ 0.,  0.,  0.,  0.]])\n'

### 创建全一数组, 同时也能指定这些特定数据的 dtype:

In [7]:
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
"""
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])
"""

D:\0ilraypan\python_work\env\pyqt5\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


'\narray([[1, 1, 1, 1],\n       [1, 1, 1, 1],\n       [1, 1, 1, 1]])\n'

### 创建全空数组, 其实每个值都是接近于零的数:

In [8]:
a = np.empty((3,4)) # 数据为empty，3行4列
"""
array([[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,
          1.48219694e-323],
       [  1.97626258e-323,   2.47032823e-323,   2.96439388e-323,
          3.45845952e-323],
       [  3.95252517e-323,   4.44659081e-323,   4.94065646e-323,
          5.43472210e-323]])
"""

'\narray([[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,\n          1.48219694e-323],\n       [  1.97626258e-323,   2.47032823e-323,   2.96439388e-323,\n          3.45845952e-323],\n       [  3.95252517e-323,   4.44659081e-323,   4.94065646e-323,\n          5.43472210e-323]])\n'

### 用arange 创建连续数组:

In [9]:
a = np.arange(10,20,2) # 10-19 的数据，2步长
"""
array([10, 12, 14, 16, 18])
"""


'\narray([10, 12, 14, 16, 18])\n'

### 使用 reshape 改变数据的形状

In [10]:
a = np.arange(12).reshape((3,4))    # 3行4列，0到11
"""
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
"""


'\narray([[ 0,  1,  2,  3],\n       [ 4,  5,  6,  7],\n       [ 8,  9, 10, 11]])\n'

### 用 linspace 创建线段型数据:

In [11]:
a = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
"""
array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])
"""


'\narray([  1.        ,   1.47368421,   1.94736842,   2.42105263,\n         2.89473684,   3.36842105,   3.84210526,   4.31578947,\n         4.78947368,   5.26315789,   5.73684211,   6.21052632,\n         6.68421053,   7.15789474,   7.63157895,   8.10526316,\n         8.57894737,   9.05263158,   9.52631579,  10.        ])\n'

### 同样也能进行 reshape 工作:

In [12]:
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
"""
array([[  1.        ,   1.47368421,   1.94736842,   2.42105263],
       [  2.89473684,   3.36842105,   3.84210526,   4.31578947],
       [  4.78947368,   5.26315789,   5.73684211,   6.21052632],
       [  6.68421053,   7.15789474,   7.63157895,   8.10526316],
       [  8.57894737,   9.05263158,   9.52631579,  10.        ]])
"""

'\narray([[  1.        ,   1.47368421,   1.94736842,   2.42105263],\n       [  2.89473684,   3.36842105,   3.84210526,   4.31578947],\n       [  4.78947368,   5.26315789,   5.73684211,   6.21052632],\n       [  6.68421053,   7.15789474,   7.63157895,   8.10526316],\n       [  8.57894737,   9.05263158,   9.52631579,  10.        ]])\n'

# Numpy 基础运算1
### numpy 的几种基本运算

In [13]:
import numpy as np
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)              # array([0, 1, 2, 3])

### 减

In [14]:
c=a-b  # array([10, 19, 28, 37])
print(c)

[10 19 28 37]


### 加

In [15]:
c=a+b   # array([10, 21, 32, 43])
print(c)

[10 21 32 43]


### 乘

In [16]:
c=a*b   # array([  0,  20,  60, 120])
print(c)

[  0  20  60 120]


### 二次方

In [17]:
c=b**2  # array([0, 1, 4, 9])
print(c)

[0 1 4 9]


### sin()

In [18]:
c=10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


### 逻辑判断

In [19]:
print(b<3)

[ True  True  True False]


### 二维矩阵

In [20]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
# array([[1, 1],
#       [0, 1]])
print(b)
# array([[0, 1],
#       [2, 3]])

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


### 矩阵相乘

In [21]:
c_dot = np.dot(a,b)
# array([[2, 4],
#       [2, 3]])
print(c_dot)

[[2 4]
 [2 3]]


### 矩阵相乘2

In [22]:
c_dot_2 = a.dot(b)
# array([[2, 4],
#       [2, 3]])
print(c_dot_2)

[[2 4]
 [2 3]]


### 数组sum(), min(), max()的使用

In [23]:
import numpy as np
a=np.random.random((2,4))
print(a)
# array([[ 0.94692159,  0.20821798,  0.35339414,  0.2805278 ],
#       [ 0.04836775,  0.04023552,  0.44091941,  0.21665268]])

[[0.19894422 0.92486149 0.45573008 0.89098198]
 [0.784036   0.23991976 0.3508115  0.9568856 ]]


In [24]:
np.sum(a)   # 4.4043622002745959

4.802170634922998

In [25]:
np.min(a)   # 0.23651223533671784

0.19894421515215666

In [26]:
np.max(a)   # 0.90438450240606416

0.9568856048120911

In [27]:
print("a =",a)
# a = [[ 0.23651224  0.41900661  0.84869417  0.46456022]
# [ 0.60771087  0.9043845   0.36603285  0.55746074]]

a = [[0.19894422 0.92486149 0.45573008 0.89098198]
 [0.784036   0.23991976 0.3508115  0.9568856 ]]


In [28]:
print("sum =",np.sum(a,axis=1))
# sum = [ 1.96877324  2.43558896]

sum = [2.47051777 2.33165287]


In [29]:
print("min =",np.min(a,axis=0))
# min = [ 0.23651224  0.41900661  0.36603285  0.46456022]

min = [0.19894422 0.23991976 0.3508115  0.89098198]


In [30]:
print("max =",np.max(a,axis=1))
# max = [ 0.84869417  0.9043845 ]

max = [0.92486149 0.9568856 ]


# Numpy 基础运算2

In [31]:
import numpy as np
A = np.arange(2,14).reshape((3,4))

# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])

print(np.argmin(A))    # 0
print(np.argmax(A))    # 11

0
11


## numpy 的几种基本运算
### 计算统计中的均值

In [32]:
print(np.mean(A))        # 7.5
print(np.average(A))     # 7.5

7.5
7.5


mean()函数还有另外一种写法：

In [33]:
print(A.mean())          # 7.5


7.5


求解中位数的函数

In [34]:
#print(A.median())       # 7.5

### 累加函数

In [35]:
print(np.cumsum(A))

# [2 5 9 14 20 27 35 44 54 65 77 90]

[ 2  5  9 14 20 27 35 44 54 65 77 90]


### 累差运算函数

In [36]:
print(np.diff(A))

# [[1 1 1]
#  [1 1 1]
#  [1 1 1]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## nonzero()函数

In [37]:
print(np.nonzero(A))

# (array([0,0,0,0,1,1,1,1,2,2,2,2]),array([0,1,2,3,0,1,2,3,0,1,2,3]))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


## 从小到大排序操作

In [38]:
import numpy as np
A = np.arange(14,2, -1).reshape((3,4))
print(A)
# array([[14, 13, 12, 11],
#       [10,  9,  8,  7],
#       [ 6,  5,  4,  3]])

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [39]:
print(np.sort(A))
# array([[11,12,13,14]
#        [ 7, 8, 9,10]
#        [ 3, 4, 5, 6]])

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


### 矩阵的转置有两种表示方法：

In [40]:
print(np.transpose(A))
print(A.T)

# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


### clip()函数

In [41]:
print(A)
# array([[14,13,12,11]
#        [10, 9, 8, 7]
#        [ 6, 5, 4, 3]])

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [42]:
print(np.clip(A,5,9))
# array([[ 9, 9, 9, 9]
#        [ 9, 9, 8, 7]
#        [ 6, 5, 5, 5]])

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


# Numpy 索引
## 一维索引

In [43]:
import numpy as np
A = np.arange(3,15)

# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

print(A[3])    # 6

6


### 矩阵转换为二维的

In [44]:
A = np.arange(3,15).reshape((3,4))
"""
array([[ 3,  4,  5,  6]
       [ 7,  8,  9, 10]
       [11, 12, 13, 14]])
"""

print(A[2])
# [11 12 13 14]

[11 12 13 14]


## 二维索引

In [45]:
print(A[1][1])      # 8
print(A[1, 1])      # 8
print(A[1, 1:3])    # [8 9]

8
8
[8 9]


In [46]:
for row in A:
    print(row)
"""
[ 3,  4,  5, 6]
[ 7,  8,  9, 10]
[11, 12, 13, 14]
"""

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


'\n[ 3,  4,  5, 6]\n[ 7,  8,  9, 10]\n[11, 12, 13, 14]\n'

In [47]:
for column in A.T:
    print(column)
"""
[ 3,  7,  11]
[ 4,  8,  12]
[ 5,  9,  13]
[ 6, 10,  14]
"""

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


'\n[ 3,  7,  11]\n[ 4,  8,  12]\n[ 5,  9,  13]\n[ 6, 10,  14]\n'

In [48]:
import numpy as np
A = np.arange(3,15).reshape((3,4))

print(A.flatten())
# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


# Numpy array 合并
## np.vstack()

In [49]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])

print(np.vstack((A,B)))    # vertical stack
"""
[[1,1,1]
 [2,2,2]]
"""


[[1 1 1]
 [2 2 2]]


'\n[[1,1,1]\n [2,2,2]]\n'

In [50]:
C = np.vstack((A,B))
print(A.shape,C.shape)

# (3,) (2,3)


(3,) (2, 3)


## np.hstack()

In [51]:
D = np.hstack((A,B))       # horizontal stack

print(D)
# [1,1,1,2,2,2]

print(A.shape,D.shape)
# (3,) (6,)

[1 1 1 2 2 2]
(3,) (6,)


## np.newaxis()

In [52]:
print(A[np.newaxis,:])
# [[1 1 1]]

print(A[np.newaxis,:].shape)
# (1,3)

print(A[:,np.newaxis])
"""
[[1]
[1]
[1]]
"""

print(A[:,np.newaxis].shape)
# (3,1)



[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [53]:
import numpy as np
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack

print(D)
"""
[[1 2]
[1 2]
[1 2]]
"""

print(A.shape,D.shape)
# (3,1) (3,2)


[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


## np.concatenate()

In [54]:
C = np.concatenate((A,B,B,A),axis=0)

print(C)
"""
array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1]])
"""

D = np.concatenate((A,B,B,A),axis=1)

print(D)
"""
array([[1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1]])
"""




[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


'\narray([[1, 2, 2, 1],\n       [1, 2, 2, 1],\n       [1, 2, 2, 1]])\n'

# Numpy array 分割
## 创建数据

In [55]:
import numpy as np
A = np.arange(12).reshape((3, 4))
print(A)
"""
array([[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]])
"""

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


'\narray([[ 0,  1,  2,  3],\n    [ 4,  5,  6,  7],\n    [ 8,  9, 10, 11]])\n'

## 纵向分割

In [56]:
print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


'\n[array([[0, 1],\n        [4, 5],\n        [8, 9]]), array([[ 2,  3],\n        [ 6,  7],\n        [10, 11]])]\n'

## 横向分割

In [57]:
print(np.split(A, 3, axis=0))

# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]




[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


# 错误分割

In [58]:
#print(np.split(A, 3, axis=1))

# ValueError: array split does not result in an equal division

## 不等量的分割

In [59]:
print(np.array_split(A, 3, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]
"""


[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


'\n[array([[0, 1],\n        [4, 5],\n        [8, 9]]), array([[ 2],\n        [ 6],\n        [10]]), array([[ 3],\n        [ 7],\n        [11]])]\n'

## 其他的分割方式



In [60]:
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))

# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [61]:
print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


'\n[array([[0, 1],\n       [4, 5],\n       [8, 9]]), array([[ 2,  3],\n        [ 6,  7],\n        [10, 11]])]\n'

# Numpy copy & deep copy
## = 的赋值方式会带有关联性

In [62]:
import numpy as np

a = np.arange(4)
# array([0, 1, 2, 3])

b = a
c = a
d = b


In [63]:
a[0] = 11
print(a)
# array([11,  1,  2,  3])

[11  1  2  3]


In [64]:
b is a  # True

True

In [65]:
c is a  # True

True

In [66]:
d is a  # True

True

In [67]:
d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)            # array([11, 22, 33,  3])


[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


## copy() 的赋值方式没有关联性


In [68]:
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
